#config = {
#	host: "search-btm-elasticsearch-test-auosztlx3finjsocnyxs4hejeq.us-west-2.es.amazonaws.com",
#	transport_options {
#		request: {timeout: 5}
#	},
#}

if File.exists("config/elasticsearch.yml")
	config.merge!(YAML.load_file("config/elasticsearch.yml").symbolize_keys)
end

Elasticsearch::Model.client = Elasticsearch::Client.new(config)